# Generated by Django 2.1.4 on 2018-12-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('win_streak', models.IntegerField(default=0)),
                ('last_match', models.BooleanField(default=False)),
                ('last_p1', models.CharField(max_length=20)),
                ('last_p2', models.CharField(max_length=20)),
                ('last_p3', models.CharField(max_length=20)),
            ],
        ),
    ]
