# Generated by Django 2.1.4 on 2018-12-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='last_p1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='records',
            name='last_p2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='records',
            name='last_p3',
            field=models.CharField(default='', max_length=20),
        ),
    ]
