# Generated by Django 2.1.4 on 2018-12-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181230_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='p1_model',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='p2_model',
            field=models.TextField(default=''),
        ),
    ]
