# Generated by Django 2.1.4 on 2018-12-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181230_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='c1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='c2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='cur_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='cur_player',
            field=models.TextField(default=''),
        ),
    ]
