# Generated by Django 2.1.4 on 2019-01-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181231_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='res_p1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='records',
            name='res_p2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='records',
            name='res_p3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
