# Generated by Django 2.1.4 on 2019-01-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190102_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
