# Generated by Django 2.1.4 on 2019-01-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='last_match',
            field=models.TextField(default=''),
        ),
    ]
