# Generated by Django 2.1.4 on 2019-01-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190102_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='h_win_streak',
            field=models.IntegerField(default=0),
        ),
    ]
