# Generated by Django 2.1.4 on 2019-01-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_records_h_win_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cur_session',
            field=models.TextField(default=''),
        ),
    ]
