# Generated by Django 2.1.4 on 2019-01-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190112_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Records'),
        ),
    ]
