# Generated by Django 2.1.4 on 2019-01-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_users_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Records', to_field='name'),
        ),
    ]
