# Generated by Django 2.1.4 on 2019-01-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190114_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='p2',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
