# Generated by Django 2.1.4 on 2019-01-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190114_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('p1_model', models.TextField(default='')),
                ('p2_model', models.TextField(default='')),
                ('c1', models.IntegerField(default=0)),
                ('c2', models.IntegerField(default=0)),
                ('cur_num', models.IntegerField(default=0)),
                ('cur_player', models.TextField(default='')),
                ('p1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='app.Users', to_field='name')),
                ('p2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='app.Users', to_field='name')),
            ],
        ),
    ]
