# Generated by Django 2.1.4 on 2019-01-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='friends',
        ),
    ]
