# Generated by Django 2.1.4 on 2019-01-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_users_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
