# Generated by Django 2.1.4 on 2019-02-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_invite_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
